---
version: '3.2'
services:
  csvserver:
    container_name: 'csvserver'
    image: 'infracloudio/csvserver:latest'
    ports:
     - 9393:9300
    environment:
     - CSVSERVER_BORDER=Orange
    volumes:
     - "$PWD:/csvserver"
  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus:v2.22.0'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
